baseURL = "https://simonstorlschulke.github.io/website/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "Simon Storl-Schulke"
# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

[params]
  # LoveIt theme version
  description = "This is My New Hugo Site"
  version = "0.2.X"
  defaultTheme = "light"

[params.social]
  GitHub = "SimonStorlSchulke"
  Youtubechannel  = "UCA6sG3mHRYgGTNr_nxpaQvg"
  Linkedin = "simon-storl-schulke-54a56b207"
  Twitter = "simonstoschu"

# Home page config
  [params.home]
    # LoveIt NEW | 0.2.0 amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # URL of avatar shown in home page
      avatarURL = "./img/avatar.jpg"
      # LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
      title = ""
      # subtitle shown in home page
      subtitle = "Simon Storl-Schulke | 3D Generalist & Entwickler"
      # whether to use typeit animation for subtitle
      typeit = false
      # whether to show social links
      social = true
      # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
      disclaimer = ""
    # Home page posts
    [params.home.posts]
      enable = false
      # special amount of posts in each home posts page
      paginate = 6
      # LoveIt DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = false


# Header config
  [params.header]
    # desktop header mode ("fixed", "normal", "auto")
    desktopMode = "auto"
    # mobile header mode ("fixed", "normal", "auto")
    mobileMode = "auto"
    # LoveIt NEW | 0.2.0 Header title config
    [params.header.title]
      # URL of the LOGO
      logo = ""
      # title name
      name = "Simon Storl-Schulke"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      # LoveIt NEW | 0.2.5 whether to use typeit animation for title name

[menu]
  [[menu.main]]
    identifier = "about"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "About"
    url = "about/"
    weight = 1
  
  [[menu.main]]
    identifier = "skills"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Skills"
    url = "skills/"
    weight = 2
    
  [[menu.main]]
    identifier = "portfolio"
    pre = ""
    post = ""
    name = "Portfolio"
    url = "portfolio/"
    weight = 3  
    
   [[menu.main]]
    identifier = "demoreel"
    pre = ""
    post = ""
    name = "Demoreel"
    url = "demoreel/"
    weight = 4
  

  [[menu.main]]
    identifier = "projects"
    pre = ""
    post = ""
    name = "Projects"
    url = "projects/"
    weight = 5


  [[menu.main]]
    identifier = "musik"
    pre = ""
    post = ""
    name = "Musik"
    url = "music/"
    weight = 6

  [[menu.main]]
    identifier = "tutorials"
    pre = ""
    post = ""
    name = "Tutorials"
    url = "tutorials/"
    weight = 7

[markup]
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false