baseURL = "https://simonstorlschulke.github.io/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "de"
# language code
languageCode = "de"
title = "Simon Storl-Schulke"
# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

[params]
  # LoveIt theme version
  description = "Simon Storl-Schulke | 3D Generalist & Entwickler"
  version = "0.2.X"
  defaultTheme = "dark"

[params.social]
  GitHub = "SimonStorlSchulke"
  Youtubechannel  = "UCA6sG3mHRYgGTNr_nxpaQvg"
  Linkedin = "simon-storl-schulke-54a56b207"
  Twitter = "simonstoschu"

# Home page config
  [params.home]
    [params.home.profile]
      enable = true
      # URL of avatar shown in home page
      avatarURL = "/img/avatar2.jpg"
      # LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
      title = ""
      # subtitle shown in home page
      subtitle = "Simon Storl-Schulke | 3D Generalist & Entwickler"
      # whether to use typeit animation for subtitle
      typeit = false
      # whether to show social links
      social = true
      # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
      disclaimer = "Hallo ich bin Simon. Ich mache Dinge mit Medien und Computern. Ich habe Medieninformatik an der Hochschule Furtwangen studiert, was mir eine gute Grundlage in vielen Bereichen der Medienproduktion und Informatik gab, auf die ich aufbauen konnte. Meine Schwerpunkte im Studium legte dabei ich vor allem auf CGI, VFX und Spieleentwicklung. <br><br> Nachdem ich während des Studiums lange als Tutor in Computergrafik aktiv war, halte ich nun auch selbst die Vorlesung Datenverarbeitung in der Medienproduktion an der HS Furtwangen.<br><br>Nebenbei mache ich viel Musik und habe zwei wundervolle Hunde, mit denen ich durch den Schwarzwald streife."
    # Home page posts
    [params.home.posts]
      enable = true


# Header config
  [params.header]
    # desktop header mode ("fixed", "normal", "auto")
    desktopMode = "auto"
    # mobile header mode ("fixed", "normal", "auto")
    mobileMode = "auto"
    # LoveIt NEW | 0.2.0 Header title config
    [params.header.title]
      # URL of the LOGO
      logo = ""
      # title name
      name = "Simon Storl-Schulke"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      # LoveIt NEW | 0.2.5 whether to use typeit animation for title name

[params.footer]
    enable = true
    # LoveIt NEW | 0.2.0 Custom content (HTML format is supported)
    custom = '<a href="/impressum">Impressum</a>'
    # LoveIt NEW | 0.2.0 whether to show Hugo and theme info
    hugo = true
    # LoveIt NEW | 0.2.0 whether to show copyright info
    copyright = true
    # LoveIt NEW | 0.2.0 whether to show the author
    author = true
    # Site creation time
    since = 2019
    # ICP info only in China (HTML format is supported)
    icp = ""
    # license info (HTML format is supported)
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'


[markup]
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false



[languages]
  [languages.en]
    weight = 1
    title = "Simon Storl-Schulke | 3D Generalist & Developer"
    languageCode = "en"
    languageName = "en"
  [languages.en.params.home]
    [languages.en.params.home.profile]
      enable = true
      # URL of avatar shown in home page
      avatarURL = "/img/avatar2.jpg"
      # LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
      title = ""
      # subtitle shown in home page
      subtitle = "Simon Storl-Schulke | 3D Generalist & Developer"
      # whether to use typeit animation for subtitle
      typeit = false
      # whether to show social links
      social = true
      # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
      disclaimer = "Hi, I’m Simon. I do stuff with media and computers. I studied Computer Science in Media at Furtwangen University, which gave me a good foundation in many areas of media production and computer science to build upon. My focus during my studies was mainly on CGI, VFX and game development.<br><br>After being active as a tutor in computer graphics for a long time during my studies, I now teach the lecture “Data Processing in Media Production” at the HS Furtwangen.<br><br>Beyond that, I make a lot of music and have two wonderful dogs that I roam the Black Forest with."

    [languages.en.params.home.posts]
      enable = true

  [[languages.en.menu.main]]
    identifier = "skills"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Skills"
    url = "skills/"
    weight = 2
   [[languages.en.menu.main]]
    identifier = "demoreel"
    pre = ""
    post = ""
    name = "Demoreel"
    url = "demoreel/"
    weight = 3
  [[languages.en.menu.main]]
    identifier = "projects"
    pre = ""
    post = ""
    name = "Projects"
    url = "projects/"
    weight = 4
  [[languages.en.menu.main]]
    identifier = "renderings"
    pre = ""
    post = ""
    name = "Renderings"
    url = "renderings/"
    weight = 5  
  [[languages.en.menu.main]]
    identifier = "music"
    pre = ""
    post = ""
    name = "Music"
    url = "music/"
    weight = 6
  [[languages.en.menu.main]]
    identifier = "tutorials"
    pre = ""
    post = ""
    name = "Tutorials"
    url = "tutorials/"
    weight = 7

[languages.de]
    weight = 2
    title = "Simon Storl-Schulker | 3D Generalist & Entwickler"
    languageCode = "de"
    languageName = "de"
  [[languages.de.menu.main]]
    identifier = "skills"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Skills"
    url = "skills/"
    weight = 2
   [[languages.de.menu.main]]
    identifier = "demoreel"
    pre = ""
    post = ""
    name = "Demoreel"
    url = "demoreel/"
    weight = 3
  [[languages.de.menu.main]]
    identifier = "projects"
    pre = ""
    post = ""
    name = "Projekte"
    url = "projects/"
    weight = 4
  [[languages.de.menu.main]]
    identifier = "renderings"
    pre = ""
    post = ""
    name = "Renderings"
    url = "renderings/"
    weight = 5
  [[languages.de.menu.main]]
    identifier = "musik"
    pre = ""
    post = ""
    name = "Musik"
    url = "music/"
    weight = 6

  [[languages.de.menu.main]]
    identifier = "tutorials"
    pre = ""
    post = ""
    name = "Tutorials"
    url = "tutorials/"
    weight = 7