baseURL = "http://www.example.com"
title = "Simon Storl-Schulke"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[params]
author = "Simon Storl-Schulke"
description = "John Doe's personal website"
keywords = "blog,developer,personal"
info = "3D Generalist & Developer"
avatarURL = "images/avatar.jpg"
#gravatar = "john.doe@example.com"
footerContent = "Enter a text here."
dateFormat = "January 2, 2006"
hideFooter = false
hideCredits = false
hideCopyright = false
since = 2019
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "light"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Enable Twemoji
enableTwemoji = false
# Custom CSS
customCSS = []
# Custom SCSS
customSCSS = []
# Custom JS
customJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
# siteID = "ABCDE"
# serverURL = "analytics.example.com" # Default value is cdn.usefathom.com, overwrite this if you are self-hosting

# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
# domain = "example.com"
# serverURL = "analytics.example.com" # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
# [params.goatCounter]
# code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"

# If you want to use Matomo(https://matomo.org) for analytics, add this section
# [params.matomo]
# siteID = "ABCDE" # Default value is "1", overwrite this if you are cloud-hosting
# serverURL = "analytics.example.com" # For cloud-hosting, use provided URL, e.g. example.matomo.cloud

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
# [params.googleTagManager]
# id = "gid"

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'"]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/"
]
scriptsrc = ["'self'", "'unsafe-inline'", "https://www.google-analytics.com"]
prefetchsrc = ["'self'"]
# connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-github"
weight = 1
url = "https://github.com/SimonStorlSchulke/"

[[params.social]]
name = "Twitter"
icon = "fa fa-twitter"
weight = 3
url = "https://twitter.com/simonstoschu"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/simon-storl-schulke-54a56b207/"

[[params.social]]
name = "YouTube"
icon = "fa fa-youtube"
weight = 4
url = "https://www.youtube.com/channel/UCA6sG3mHRYgGTNr_nxpaQvg"


[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Skills"
weight = 2
url = "skills/"

#[[languages.en.menu.main]]
#name = "Blog"
#weight = 3
#url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 4
url = "projects/"

[[languages.en.menu.main]]
name = "Demo-Reel"
weight = 5
url = "demoreel/"

[[languages.en.menu.main]]
name = "Videos"
weight = 6
url = "videos/"

[[languages.en.menu.main]]
name = "Music"
weight = 7
url = "music/"

[[languages.en.menu.main]]
name = "Contact"
weight = 8
url = "contact/"

[languages.ger]
languageName = "🇩🇪"
title = "Simon Storl-Schulke"

[languages.ger.params]
author = "Simon Storl-Schulke"
info = "3D Generalist & Entwickler"
description = "Sítio pessoal de Simon Storl-Schulke"
keywords = "blog,desenvolvedor,pessoal"
footerContent = "Coloque algum texto aqui."

[[languages.ger.menu.main]]
name = "Über"
weight = 1
url = "about/"

[[languages.ger.menu.main]]
name = "Skills"
weight = 2
url = "skills/"

[[languages.ger.menu.main]]
name = "Projekte"
weight = 4
url = "projects/"

[[languages.ger.menu.main]]
name = "Demo-Reel"
weight = 5
url = "demoreel/"

[[languages.ger.menu.main]]
name = "Videos"
weight = 6
url = "videos/"

[[languages.ger.menu.main]]
name = "Musik"
weight = 7
url = "music/"

[[languages.ger.menu.main]]
name = "Kontakt"
weight = 8
url = "contact/"



[markup]
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false